latest_project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from finish import views as finish_views


urlpatterns = [
    path("", include("finish.urls")),
    path("admin/", admin.site.urls),
]

latest_project/finish/urls.py
from django.urls import path
from finish import views

app_name = "finish"

urlpatterns = [
    path("", views.form_test, name="search"),
    path("register/", views.register),
    path("login/", views.login),
    path("logout/", views.logout),
    path("lhome/", views.lform_test, name="lsearch"),
]

latest_project/finish/models.py
from django.db import models

# Create your models here.

class Duser(models.Model):
    objects = models.Manager()
    username = models.CharField(max_length=32, verbose_name='사용자명')
    useremail = models.EmailField(max_length=128, verbose_name='사용자 이메일')
    password = models.CharField(max_length=64, verbose_name='비밀번호')
    register_dttm = models.DateField(auto_now_add=True, verbose_name='가입날짜')

    def __str__(self):
        return self.username

    class Meta:
        db_table = 'user_define_fuser_table'
        verbose_name = '띵동 사용자'
        verbose_name_plural = '띵동 사용자'

latest_project/finish/forms.py
from django import forms
from .models import Duser
from django.contrib.auth.hashers import check_password

class LoginForm(forms.Form):
    username = forms.CharField(max_length=32, label="아이디", error_messages={'required':"아이디를 입력하세요"})
    password = forms.CharField(label="비밀번호", widget=forms.PasswordInput, error_messages={'required':"비밀번호를 입력하세요"})

    def clean(self):
        clean_data = super().clean()

        username = clean_data.get('username')
        password = clean_data.get('password')

        if username and password :
            finish = Duser.objects.get(username=username)

            if not check_password(password, finish.password) :
                self.add_error('password', '비밀번호가 틀렸습니다.')
            else :
                self.user_id = finish.id    

latest_project/finish/views.py
from django.shortcuts import render, redirect
from .models import Duser
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.hashers import make_password, check_password
from .forms import LoginForm
from .crawling import danggn
from .crawling import hellomarket
from .crawling import sellit


def form_test(request):
    if request.method == "GET":
        return render(request, "index.html")
    elif request.method == "POST":
        search = request.POST["search"]
        dgimgurl, dgdata, dgtitle, dgcost = danggn(search)
        himgurl, hdata, htitle, hcost = hellomarket(search)
        simgurl, sdata, stitle, scost = sellit(search)

        return render(
            request,
            "index.html",
            context={
                "dgimgurl": dgimgurl,
                "dgdata": dgdata,
                "dgtitle": dgtitle,
                "dgcost": dgcost,
                "himgurl": himgurl,
                "hdata": hdata,
                "htitle": htitle,
                "hcost": hcost,
                "simgurl": simgurl,
                "sdata": sdata,
                "stitle": stitle,
                "scost": scost,
            },
        )


def lform_test(request):
    if request.method == "GET":
        return render(request, "logindex.html")
    elif request.method == "POST":
        search = request.POST["lsearch"]
        dgimgurl, dgdata, dgtitle, dgcost = danggn(search)
        himgurl, hdata, htitle, hcost = hellomarket(search)
        simgurl, sdata, stitle, scost = sellit(search)

        return render(
            request,
            "logindex.html",
            context={
                "dgimgurl": dgimgurl,
                "dgdata": dgdata,
                "dgtitle": dgtitle,
                "dgcost": dgcost,
                "himgurl": himgurl,
                "hdata": hdata,
                "htitle": htitle,
                "hcost": hcost,
                "simgurl": simgurl,
                "sdata": sdata,
                "stitle": stitle,
                "scost": scost,
            },
        )


def register(request):
    if request.method == "GET":
        return render(request, "register.html")
    elif request.method == "POST":
        username = request.POST.get("username", None)
        password = request.POST.get("password", None)
        re_password = request.POST.get("re_password", None)
        useremail = request.POST.get("useremail", None)

        res_data = {}
        if not (username and password and re_password and useremail):
            res_data["error"] = "모든 값을 입력하시오."
        elif password != re_password:
            # return HttpResponse("비밀번호가 다름")
            res_data["error"] = "비밀번호가 다름"
        else:
            finish = Duser(
                username=username,
                password=make_password(password),
                useremail=useremail,
            )

            finish.save()

        return render(request, "register.html", res_data)


def login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            request.session["user"] = form.user_id

            return render(request, "logindex.html", {"form": form})
    else:
        form = LoginForm()
    return render(request, "login.html", {"form": form})


def logout(request):
    if request.session["user"]:
        del request.session["user"]

    return redirect("/")

latest_project/finish/templates/index.html
{% load template_custom %}
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>DDINGDONG - SHOP</title>
  <link rel="icon" href='{% static "img/dFevicon.png" %}' type="image/png" />
  <link rel="stylesheet" href='{% static "vendors/bootstrap/bootstrap.min.css" %}' />
  <link rel="stylesheet" href='{% static "vendors/fontawesome/css/all.min.css" %}' />
  <link rel="stylesheet" href='{% static "vendors/themify-icons/themify-icons.css" %}' />
  <link rel="stylesheet" href='{% static "vendors/nice-select/nice-select.css" %}' />
  <link rel="stylesheet" href='{% static "vendors/owl-carousel/owl.theme.default.min.css" %}' />
  <link rel="stylesheet" href='{% static "vendors/owl-carousel/owl.carousel.min.css" %}' />

  <link rel="stylesheet" href='{% static "css/style.css" %}' />

  <!-- CODELAB: Add link rel manifest -->
  <link rel="manifest" href="/finish/templates/manifest.json">

  <!-- CODELAB: Add iOS meta tags and icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="DDINGDONG">
  <link rel="apple-touch-icon" href="/static/img/icons/icon-152x152.png">

  <!-- CODELAB: Add description here -->
  <meta name="description" content="통합 중고 제품 검색" />

  <!-- CODELAB: Add meta theme-color -->
  <meta name="theme-color" content="#0E6EEB" />
</head>

<body>
  <div style="overflow:scroll; width:100%; height:1000px;">
    <!--================ Start Header Menu Area =================-->
    <header class="header_area">
      <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container">
            <a class="navbar-brand logo_h" href="">
              <img src='{% static "img/dlogo.png" %}' alt="" /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
              <ul class="nav navbar-nav menu_nav ml-auto mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="">Home</a>
                </li>
                <li class="nav-item submenu dropdown">
                  <a href="index" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                    aria-haspopup="true" aria-expanded="false">Shop</a>
                  <ul class="dropdown-menu">
                    <li class="nav-item">
                      <a class="nav-link" href="https://www.daangn.com/">당근마켓</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="https://www.hellomarket.com/">헬로마켓</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="https://www.withsellit.com/">셀잇</a>
                    </li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="mypage.html">MyPage</a>
                </li>
              </ul>

              <ul class="nav-shop">
                <li class="nav-item">
                  <a class="button button-header" href="/login">Login</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>
    <!--================ End Header Menu Area =================-->

    <!-- ================ start banner area ================= -->
    <section class="blog-banner-area" id="category">
      <div class="container h-100">
        <div class="blog-banner">
          <div class="text-center">
            <h1>Search Items</h1>
            <nav aria-label="breadcrumb" class="banner-breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">DDINGDONG</a></li>
                <li class="breadcrumb-item active" aria-current="page">
                  PROJECT
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section>
    <!-- ================ end banner area ================= -->

    <!-- ================ category section start ================= -->
    <section class="section-margin--small mb-5">
      <div class="container">
        <div class="row">

          <div class="col-xl-9 col-lg-8 col-md-7">
            <!-- Start Filter Bar -->
            <div class="filter-bar d-flex flex-wrap align-items-center">
              <div>
                <div class="input-group filter-bar-search">
                  <form action="{% url 'finish:search' %}" method="post">
                    {% csrf_token %}
                    <input class="input" name="search" id="inputFocus" type="text" placeholder="Search"
                      value="{{search}}" />
                    <button type="submit"><i class="ti-search"></i></button>
                  </form>
                </div>
              </div>
            </div>
            <!-- End Filter Bar -->
            <!-- Start Best Seller -->
            <section class="lattest-product-area pb-40 category-list">

              <div class="row">
                {% for i in "x"|rjust:"6" %}
                {% dg_item dgimgurl dgdata dgtitle dgcost as danggn%}
                <div class="col-md-6 col-lg-4">
                  <div class="card text-center card-product">
                    <a href="{{danggn.1}}">{{danggn.2}}
                      <div>
                        <img src="{{danggn.0}}" alt="{{danggn.0}}" style="width: 100%; height: auto;">
                      </div>
                      <div class="card-body">
                        <h4 class="card-product__title"></h4>

                      </div>
                    </a>
                    <p class="card-product__price">{{danggn.3}}</p>
                  </div>
                </div>
                {%endfor %}
              </div>




              <div class="row">
                {% for i in "x"|rjust:"6" %}
                {% h_item himgurl hdata htitle hcost as hello %}
                <div class="col-md-6 col-lg-4">
                  <div class="card text-center card-product">
                    <a href="{{hello.1}}">{{hello.2}}
                      <div>
                        <img src="{{hello.0}}" alt="{{hello.0}}" style="width: 100%; height: auto;">
                      </div>
                      <div class="card-body">
                        <h4 class="card-product__title"></h4>

                      </div>
                    </a>
                    <p class="card-product__price">{{hello.3}}</p>
                  </div>
                </div>
                {%endfor %}
              </div>



              <div class="row">
                {% for i in "x"|rjust:"6" %}
                {% s_item simgurl sdata stitle scost as sellit %}
                <div class="col-md-6 col-lg-4">
                  <div class="card text-center card-product">
                    <a href="{{sellit.1}}">{{sellit.2}}
                      <div>
                        <img src="{{sellit.0}}" alt="{{sellit.0}}" style="width: 100%; height: auto;">
                      </div>
                      <div class="card-body">
                        <h4 class="card-product__title"></h4>

                      </div>
                    </a>
                    <p class="card-product__price">{{sellit.3}}</p>
                  </div>
                </div>
                {%endfor %}
              </div>

            </section>
            <!-- End Best Seller -->
          </div>
        </div>
      </div>
    </section>
    <!-- ================ category section end ================= -->

    <!--================ Start footer Area  =================-->
    <footer>
      <div class="footer-area">
        <div class="container">
          <div class="row section_gap">
            <div class="col-lg-3 col-md-6 col-sm-6">
              <div class="single-footer-widget tp_widgets">
                <h4 class="footer_title large_title">OUR PROJECT</h4>
                <p>
                  크롤링을 이용한 통합 환경 중고 제품 서칭 애플리케이션 제작 프로젝트
                </p>
                <p>
                  컴퓨터공학과 <br />
                  201535003 강성구 <br />
                  201535004 강영욱 <br />
                  201535024 용석주
                </p>
              </div>
            </div>

            <div class="offset-lg-1 col-lg-3 col-md-6 col-sm-6">
              <div class="single-footer-widget tp_widgets">
                <h4 class="footer_title">Contact Us</h4>
                <div class="ml-40">
                  <p class="sm-head">
                    <span class="fa fa-location-arrow"></span>
                    성공회대학교
                  </p>
                  <p>08359 서울시 구로구 연동로 320</p>

                  <p class="sm-head">
                    <span class="fa fa-phone"></span>
                    전화
                  </p>
                  <p>
                    T. 02-2610-4114 <br />
                    F. 02-2683-8858
                  </p>

                  <p class="sm-head">
                    <span class="fa fa-envelope"></span>
                    이메일
                  </p>
                  <p>
                    ddingdong@skhu.ac.kr
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-header">

        <!-- Header section containing title -->


        <div class="footer-bottom">
          <div class="container">
            <div class="row d-flex">
              <p class="col-lg-12 footer-text text-center">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;
                <script>
                  document.write(new Date().getFullYear());
                </script>
                All rights reserved | This template is made with
                <i class="fa fa-heart" aria-hidden="true"></i> by
                <a href="https://colorlib.com" target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              </p>
            </div>
          </div>
        </div>
    </footer>
    <!--================ End footer Area  =================-->

    <script src='{% static "vendors/jquery/jquery-3.2.1.min.js" %}'></script>
    <script src='{% static "vendors/bootstrap/bootstrap.bundle.min.js" %}'></script>
    <script src='{% static "vendors/skrollr.min.js" %}'></script>
    <script src='{% static "vendors/owl-carousel/owl.carousel.min.js" %}'></script>
    <script src='{% static "vendors/nice-select/jquery.nice-select.min.js" %}'></script>
    <script src='{% static "vendors/jquery.ajaxchimp.min.js" %}'></script>
    <script src='{% static "vendors/mail-script.js" %}'></script>
    <script src='{% static "js/main.js" %}'></script>
  </div>
</body>

</html>

latest_project/finish/templates/logindex.html
{% load template_custom %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<div style="overflow:scroll; width:100%; height:1000px;">

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>DDINGDONG - SHOP</title>
    <link rel="icon" href='{% static "img/dFevicon.png" %}' type="image/png" />
    <link rel="stylesheet" href='{% static "vendors/bootstrap/bootstrap.min.css" %}' />
    <link rel="stylesheet" href='{% static "vendors/fontawesome/css/all.min.css" %}' />
    <link rel="stylesheet" href='{% static "vendors/themify-icons/themify-icons.css" %}' />
    <link rel="stylesheet" href='{% static "vendors/nice-select/nice-select.css" %}' />
    <link rel="stylesheet" href='{% static "vendors/owl-carousel/owl.theme.default.min.css" %}' />
    <link rel="stylesheet" href='{% static "vendors/owl-carousel/owl.carousel.min.css" %}' />

    <link rel="stylesheet" href='{% static "css/style.css" %}' />
    <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
  </head>

  <body>
    <!--================ Start Header Menu Area =================-->
    <header class="header_area">
      <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container">
            <a class="navbar-brand logo_h" href="/lhome">
              <img src='{% static "img/dlogo.png" %}' alt="" /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
              <ul class="nav navbar-nav menu_nav ml-auto mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="/lhome">Home</a>
                </li>
                <li class="nav-item submenu dropdown">
                  <a href="index" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                    aria-haspopup="true" aria-expanded="false">Shop</a>
                  <ul class="dropdown-menu">
                    <li class="nav-item">
                      <a class="nav-link" href="https://www.daangn.com/">당근마켓</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="https://www.hellomarket.com/">헬로마켓</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="https://www.withsellit.com/">셀잇</a>
                    </li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="mypage.html">MyPage</a>
                </li>
              </ul>

              <ul class="nav-shop">
                <li class="nav-item">
                  <a class="button button-header" href="/logout">Logout</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>
    <!--================ End Header Menu Area =================-->

    <!-- ================ start banner area ================= -->
    <section class="blog-banner-area" id="category">
      <div class="container h-100">
        <div class="blog-banner">
          <div class="text-center">
            <h1>Search Items</h1>
            <nav aria-label="breadcrumb" class="banner-breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">DDINGDONG</a></li>
                <li class="breadcrumb-item active" aria-current="page">
                  PROJECT
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section>
    <!-- ================ end banner area ================= -->

    <!-- ================ category section start ================= -->
    <section class="section-margin--small mb-5">
      <div class="container">
        <div class="row">

          <div class="col-xl-9 col-lg-8 col-md-7">
            <!-- Start Filter Bar -->
            <div class="filter-bar d-flex flex-wrap align-items-center">
              <div>
                <div class="input-group filter-bar-search">
                  <form action="{% url 'finish:search' %}" method="post">
                    {% csrf_token %}
                    <input class="input" name="search" id="inputFocus" type="text" placeholder="Search"
                      value="{{search}}" />
                    <button type="submit"><i class="ti-search"></i></button>
                  </form>
                </div>
              </div>
            </div>
            <!-- End Filter Bar -->
            <!-- Start Best Seller -->
            <section class="lattest-product-area pb-40 category-list">

              <div class="row">
                {% for i in "x"|rjust:"6" %}
                {% dg_item dgimgurl dgdata dgtitle dgcost as danggn%}
                <div class="col-md-6 col-lg-4">
                  <div class="card text-center card-product">
                    <a href="{{danggn.1}}">{{danggn.2}}
                      <div>
                        <img src="{{danggn.0}}" alt="{{danggn.0}}" style="width: 100%; height: auto;">
                      </div>
                      <div class="card-body">
                        <h4 class="card-product__title"></h4>
                        <p class="card-product__price">{{danggn.3}}</p>
                      </div>
                    </a>
                  </div>
                </div>
                {%endfor %}
              </div>




              <div class="row">
                {% for i in "x"|rjust:"6" %}
                {% h_item himgurl hdata htitle hcost as hello %}
                <div class="col-md-6 col-lg-4">
                  <div class="card text-center card-product">
                    <a href="{{hello.1}}">{{hello.2}}
                      <div>
                        <img src="{{hello.0}}" alt="{{hello.0}}" style="width: 100%; height: auto;">
                      </div>
                      <div class="card-body">
                        <h4 class="card-product__title"></h4>
                        <p class="card-product__price">{{hello.3}}</p>
                      </div>
                    </a>
                  </div>
                </div>
                {%endfor %}
              </div>



              <div class="row">
                {% for i in "x"|rjust:"6" %}
                {% s_item simgurl sdata stitle scost as sellit %}
                <div class="col-md-6 col-lg-4">
                  <div class="card text-center card-product">
                    <a href="{{sellit.1}}">{{sellit.2}}
                      <div>
                        <img src="{{sellit.0}}" alt="{{sellit.0}}" style="width: 100%; height: auto;">
                      </div>
                      <div class="card-body">
                        <h4 class="card-product__title"></h4>
                        <p class="card-product__price">{{sellit.3}}</p>
                      </div>
                    </a>
                  </div>
                </div>
                {%endfor %}
              </div>

            </section>
            <!-- End Best Seller -->
          </div>
        </div>
      </div>
    </section>
    <!-- ================ category section end ================= -->

    <!--================ Start footer Area  =================-->
    <footer>
      <div class="footer-area">
        <div class="container">
          <div class="row section_gap">
            <div class="col-lg-3 col-md-6 col-sm-6">
              <div class="single-footer-widget tp_widgets">
                <h4 class="footer_title large_title">OUR PROJECT</h4>
                <p>
                  크롤링을 이용한 통합 환경 중고 제품 서칭 애플리케이션 제작 프로젝트
                </p>
                <p>
                  컴퓨터공학과 <br />
                  201535003 강성구 <br />
                  201535004 강영욱 <br />
                  201535024 용석주
                </p>
              </div>
            </div>

            <div class="offset-lg-1 col-lg-3 col-md-6 col-sm-6">
              <div class="single-footer-widget tp_widgets">
                <h4 class="footer_title">Contact Us</h4>
                <div class="ml-40">
                  <p class="sm-head">
                    <span class="fa fa-location-arrow"></span>
                    성공회대학교
                  </p>
                  <p>08359 서울시 구로구 연동로 320</p>

                  <p class="sm-head">
                    <span class="fa fa-phone"></span>
                    전화
                  </p>
                  <p>
                    T. 02-2610-4114 <br />
                    F. 02-2683-8858
                  </p>

                  <p class="sm-head">
                    <span class="fa fa-envelope"></span>
                    이메일
                  </p>
                  <p>
                    ddingdong@skhu.ac.kr
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-header">

        <!-- Header section containing title -->



        <div class="footer-bottom">
          <div class="container">
            <div class="row d-flex">
              <p class="col-lg-12 footer-text text-center">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;
                <script>
                  document.write(new Date().getFullYear());
                </script>
                All rights reserved | This template is made with
                <i class="fa fa-heart" aria-hidden="true"></i> by
                <a href="https://colorlib.com" target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              </p>
            </div>
          </div>
        </div>
    </footer>
    <!--================ End footer Area  =================-->

    <script src='{% static "vendors/jquery/jquery-3.2.1.min.js" %}'></script>
    <script src='{% static "vendors/bootstrap/bootstrap.bundle.min.js" %}'></script>
    <script src='{% static "vendors/skrollr.min.js" %}'></script>
    <script src='{% static "vendors/owl-carousel/owl.carousel.min.js" %}'></script>
    <script src='{% static "vendors/nice-select/jquery.nice-select.min.js" %}'></script>
    <script src='{% static "vendors/jquery.ajaxchimp.min.js" %}'></script>
    <script src='{% static "vendors/mail-script.js" %}'></script>
    <script src='{% static "js/main.js" %}'></script>
</div>
</body>

</html>